# Uncomment the next line to define a global platform for your project
# source 'https://github.com/cocoapods/specs'
platform :ios, '10.3'
use_frameworks!

target 'pokedex3' do
pod 'Alamofire', '~> 5.2'
end

